webjars:
  bootstrap: "4.3.1"
  jquery: "3.4.1"
spring:  datasource:    url: "jdbc:mysql://127.0.0.1/test"
    username: "root"
    password: "password"
    driver-class-name: "com.mysql.jdbc.Driver"
