webjars:
  bootstrap: "4.3.1"
  jquery: "3.4.1"
spring:  datasource:    url: "jdbc:mysql://127.0.0.1/test?serverTimezone=JST"
    username: "root"
    password: "password"
    driver-class-name: "com.mysql.jdbc.Driver"  flyway:    enabled: false
mybatis:
  mapper-locations: db/datasource/*
  type-aliases-package: com.github.apz.model
  type-handlers-package: com.github.apz.datasource.typehandler
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.github.apz.datasource: TRACE
server:
  servlet:
    context-path: /chain-pack